#!/bin/sh
#
# Copyright 2016 - 2018  Ternaris.
# SPDX-License-Identifier: AGPL-3.0-only

set -e

cd "$(dirname "$(realpath "$0")")"/../docs

sphinx-build --help >/dev/null 2>&1 || (
    echo "ERROR: sphinx-build is not available, have you activated the virtualenv?"
    exit 1
)
marv --help >/dev/null 2>&1 || (
    echo "ERROR: marv is not available, have you activated the virtualenv?"
    exit 1
)

make clean
make html
rm -rf ../code/marv-robotics/marv_robotics/docs
cp -a ./_build/html ../code/marv-robotics/marv_robotics/docs
