#!/usr/bin/env bash
#
# Copyright 2016 - 2018  Ternaris.
# SPDX-License-Identifier: AGPL-3.0-only

set -e

usage() {
    echo
    echo "Usage: run-container SITE SCANROOT [EXTRA_OPTS ...]"
    echo
    echo "The site is expected to contain marv.conf and uwsgi.conf."
    echo "It is mounted inside the container at /home/marv/site."
    echo
    echo "The scanroot contains the log files for one or more collections."
    echo "It is mounted read-only into the container at /scanroot."
    echo
    echo "All additional arguments are passed as options to docker run."
    echo
    exit 1
}

if [[ -n "$DEBUG" ]]; then
    set -x
fi

cd "$(dirname "$(realpath "$0")")"/..

SITE="$1"; shift || usage
SCANROOT="$1"; shift || usage
[[ -d "$SCANROOT" ]] || usage
SCANROOT="$(realpath "$SCANROOT")"

BASENAME="$(basename "$PWD")"
NAME="${MARV_CONTAINER_NAME:-$BASENAME}"
HOSTNAME="${NAME//./-}"
HTTP="${MARV_HTTP:-127.0.0.1:8000}"

if [[ -n "$MARV_IMAGE" ]]; then
    IMAGE="$MARV_IMAGE"
elif [[ -e .image-name ]]; then
    IMAGE="$(<.image-name)"
else
    IMAGE="$BASENAME"
fi

get_timezone() {
    tz=$(cat /etc/timezone 2>/dev/null|| true)
    if [[ -z "$tz" ]]; then
	link=$(realpath /etc/localtime)
	tz="$(basename "$(dirname "$link")")/$(basename "$link")"
    fi
    echo $tz
}

export TIMEZONE="${MARV_TIMEZONE:-$(get_timezone)}"

docker stop "$NAME" || true
docker rm "$NAME" || true
docker run \
       --name "$NAME" \
       --hostname "$HOSTNAME" \
       --restart unless-stopped \
       -e COLORFGBG \
       -e "DEVELOP=${DEVELOP:+/home/marv/code}" \
       -e DEBUG \
       -e MARV_APPLICATION_ROOT \
       -e MARV_INIT \
       -e TERM \
       -e TIMEZONE \
       -p "$HTTP:8000" \
       -v "$PWD/code:/home/marv/code" \
       -v "$PWD/docs:/home/marv/docs" \
       -v "$PWD/scripts:/home/marv/scripts" \
       -v "$PWD/tutorial:/home/marv/tutorial" \
       -v "$PWD/CHANGES.rst:/home/marv/CHANGES.rst" \
       -v "$(realpath "$SITE"):/home/marv/site" \
       -v "$(realpath "$SCANROOT"):/scanroot:ro" \
       "$@" \
       "$IMAGE"
