#!/usr/bin/env bash
#
# Copyright 2016 - 2018  Ternaris.
# SPDX-License-Identifier: AGPL-3.0-only

set -e

usage() {
    echo
    echo "Usage: setup-venv REQUIREMENTS TARGET"
    echo
    echo "Example: ./scripts/setup-venv requirements/marv-robotics.txt venv"
    echo
    exit 1
}

REQUIREMENTS="$1"; shift || usage
TARGET="$1"; shift || usage
EXTRA_CODE="$1"  # intentionally undocumented and subject to change
if [[ -n "$EXTRA_CODE" ]]; then
    EXTRA_CODE="$(realpath "$EXTRA_CODE")"
fi
[[ ! -d "$TARGET" ]] || (echo "The target directory must not exist, yet."; exit 1)
PIP_ARGS=${PIP_ARGS:--e}  # develop install by default

REQUIREMENTS="$(realpath "$REQUIREMENTS")"
TARGET="$(realpath "$TARGET")"

cd "$(dirname "$(realpath "$0")")"/..

python3.7 -m venv "$TARGET"
"$TARGET"/bin/pip install -U pip==19.2.3 setuptools==41.2.0 wheel==0.33.6
"$TARGET"/bin/pip install -Ur "$REQUIREMENTS"
"$TARGET"/bin/pip install -Ur requirements/develop.txt

# Install all python distributions directly in code
find code -maxdepth 2 -name setup.py -execdir "$TARGET"/bin/pip install --no-deps $PIP_ARGS . \;

if [[ -n "$EXTRA_CODE" ]]; then
    find "$EXTRA_CODE" -maxdepth 2 -name setup.py -execdir "$TARGET"/bin/pip install --no-deps $PIP_ARGS . \;
fi

# marv-ludwig is installed from PyPI as a dependency of marv-robotics
"$TARGET"/bin/pip install -e code/marv-robotics
